### ISSUE TITLE
Fix permalinks for pages

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#11]
Permalinks for pages displayed in the backend won't load the page.
<img width="816" alt="screenshot 2015-11-09 11 53 45" src="https://cloud.githubusercontent.com/assets/1880844/11030783/f1b7a01a-86d8-11e5-83d8-aa147f9f1fc5.png">

The right path for the about page right now (working fine in the main nav) is https://feelingrestful.com/page/about/

Add redirects maybe?

**Comment by joehoyle** [comment]
Fixed
