### ISSUE TITLE
Dev tools covering content for logged in users

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#12]
The list of posts gets hidden behind the request viewer on https://feelingrestful.com/news/ and there isn't a way to see all of the content. 

Post titles are not active in the `/news` and individual posts don't seem to work as reported in #9. Connected to #11 maybe?

<img width="1280" alt="screenshot 2015-11-09 12 11 58" src="https://cloud.githubusercontent.com/assets/1880844/11031173/3aed57e6-86db-11e5-91d7-c08eb1e97cdb.png">

**Comment by petyaraykovska** [comment]
Sponsors page has the same problem: 

<img width="1280" alt="screenshot 2015-11-09 12 34 36" src="https://cloud.githubusercontent.com/assets/1880844/11031596/57d9a00a-86de-11e5-92dc-68d989ba7eaa.png">

**Comment by petyaraykovska** [comment]
Renaming that issue as these are dev tools and the page should work fine for not logged users. It would be nice to fix for logged users as well though.

**Comment by joehoyle** [comment]
Fixed
