### ISSUE TITLE
Add sponsorship packages to the sponsors page

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#13]
As Sponsors no longer seems to be a page, let's please link the sponsorship packages before all other content on https://feelingrestful.com/sponsors/.

Is there a way to add a button with a `Download our sponsorship packages`? If there is, let's do it, if it's hard, let's at least get a visible link on top of the logos that downloads the PDF.

The header should say:

> ### Interested in sponsoring A DAY OF REST?
> 
> [Download The Sponsorship packages](https://hmn-uploads.s3.amazonaws.com/humanmade-production/uploads/sites/27/2015/11/DAYRESTSponsor.pdf)

Here are the packages: https://hmn-uploads.s3.amazonaws.com/humanmade-production/uploads/sites/27/2015/11/DAYRESTSponsor.pdf

Let's add this paragraph at the bottom as well:

> We’d love to see your company name here. [Download The Sponsorship packages](https://hmn-uploads.s3.amazonaws.com/humanmade-production/uploads/sites/27/2015/11/DAYRESTSponsor.pdf) and [Get in touch](https://feelingrestful.com/page/contact/) to reserve your preferred sponsor option for A Day of REST.

**Comment by petyaraykovska** [comment]
The second part of this issue is done, can we please add the link above the list of sponsors as well? Thanks!

**Comment by tareiking** [comment]
@petyaraykovska will this complete the top bit? I played it down (without using headers) as I didn't want to draw away too much from the actual sponsors content 

![](https://cloudup.com/cD8379s42Ne+)

**Comment by petyaraykovska** [comment]
That works great, Tarei, thank you!

**Comment by petyaraykovska** [comment]
Fixed :rocket:
