### ISSUE TITLE
Activate speaker pictures to link to the speaker profile

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#15]
Right now we only have the name of the speaker link to their profile. Let's get the image to link to the profile as well to make it easier for users to get to the profile.

**Comment by noeltock** [comment]
This was a technical challenge that wasn't fun. Mainly because we wanted to colour the images in. Remove the colour filtering (blue) and it can be that way again.

—
Sent with my thumbs

**Comment by petyaraykovska** [comment]
It's a nice to have. If it's a pain, happy to skip it.

**Comment by noeltock** [comment]
Choose one :)
- Upload blue pics & remove blue filter
- Remove blue filter
- Leave as is

**Comment by joehoyle** [comment]
Fixed
