### ISSUE TITLE
Adding a new sponsor prevents the sponsor page from loading

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#17]
I added a new sposnors entry, but after publishing the whole sponsors page couldn't load. Is that because of the missing image?

Anything specific that needs to be taken into account when adding sponsors? Is that something we can still manage manually?

**Comment by joehoyle** [comment]
Fixed - turns out the theme didn't have `post-thumbnails` support, I also fixed the sponsors page so it doesn't break if the sponsor doesn't have a featured image.
