### ISSUE TITLE
Add microsponsor tier

### ISSUE THREAD

**Issue by smckeown** [humanmade/feelingrestful-theme#21]
We need a microsponsor tier for the sponsor page. This should just be small logos that link to a website. 

I tried adding one but it appeared at the top of the page. Microsponsors should be below the other sponsors.

**Comment by joehoyle** [comment]
@smckeown they should now appear at the bottom of the page, however we don't have any different design right now for them - we could probably get them up there still, and see how we can iterate on that.

**Comment by petyaraykovska** [comment]
Fixed
