### ISSUE TITLE
Page builder doesn't save modules

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#29]
Adding a module has stopped working in the page builder. The result of this is that I can not create new pages or update the content of current ones.

Steps to recreate:
- Create new page
- Add header module
- Click on "Save as a draft"
- Module disappears
## What I've tried so far:
- Tried publishing the page instead of saving as a draft - the result is the same
- Tried adding a different module, tested adding content using all the available modules - the result is the same
- Tried previewing the page - that doesn't work
## What I haven't tried:
- Adding a module to an existing page - I'm afraid it might cause the current content to disappear.

This is an issue with a critical priority as the schedule has to go out on Monday. Is there a way we can find out what happened, what broke and at least revert that so we can use the page builder? 

If not, can we get pages to use the standard text editor? 

CC-ing @mattheu here for help as well as you are our page builder guru :)

// @sanchothefat @joehoyle

**Comment by mattheu** [comment]
Looks like the preview post meta data broke saving the data...

cc @sanchothefat

**Comment by roborourke** [comment]
My bad, fixed in #30
