### ISSUE TITLE
Theme Redesign Homestretch

### ISSUE THREAD

**Issue by noeltock** [humanmade/feelingrestful-theme#3]
Spent the last day redesigning the entire site based off of Joe's strong foundation. Here is the remaining goodness imho.

**Design / Frontend ( @noeltock )**
- [x] Prefix pass / clean-up
- [x] _Loading_ styles
- [x] API request pop-up
- [ ] OG data for homepage

**Development / Backend ( @joehoyle )**
- [x] Replicate loading design across pages (~~pending design Noel~~)
- [x] Get API request to show on front page / initial load
- [x] Get mobile navigation to work (design is all there , make `.menu-toggle` toggle `.menu` )
- [x] Link new contact page (pending content Petya)
- [x] API request pop-up (~~pending design Noel~~)

**Editorial ( @petyaraykovska / @smckeown  )**
- [x] Create contact page with any contact details, we won't be developing a contact form at this point so best to push people to email and facebook.
- [x] Latest post _We Have a New Venue!_ has an empty paragraph at the top, needs to be removed
- [x] Sponsor logos are not edge to edge, this is really important when you want consistent images. Can someone please re-upload all (except WP Engine) to be edge to edge (i.e. no white space around).
- [ ] In-kind sponsors area for Mozilla.
- [x] _Opinion_ About page first paragraph lacks scale/importance of REST API. Any media quotes? Which big names are using it? etc.
- [x] Post Status needs to be linked in About page

**Cherry on the cake / not the end of the world**
- [x] Get white sponsor logo's so we can incorporate on front-page (and make sponsors page nicer in general). Every company has a white/monotone version and is used to it. Hiding them on a sponsors page is a bit counter-intuitive (larger, more established conf's have that leeway, but we're not them).
- [ ] Align blue colour in photos and video so that we're not using a hacky workaround (CSS) which makes it look weird.

_(will add more here as anything comes up)_

**Comment by petyaraykovska** [comment]
Added other things as well:
- [x] Fixed the about page with the correct address, it was still stating Bishopsgate
- [x] Removed the map as it's not working yet
- [x] Added link to Twitter on the Contact page
- [x] Added sponsorship packages and contact link to the Contact page

**Comment by noeltock** [comment]
Thanks guys, once we do the final few fixes from @petyaraykovska and get Mozilla on there, I'll take on Stripe & Dreamhost for the large slots.

**Comment by petyaraykovska** [comment]
@smckeown Do you want me to do the sponsorship logos? You mentioned yesterday you're doing them, but I can do them if need be?

**Comment by petyaraykovska** [comment]
@noeltock Sponsors logos edge to edge: https://www.dropbox.com/sh/epyxxnvy1amgb43/AADKjmiFJxJ_dsIbv0-87aHaa?dl=0
