### ISSUE TITLE
Add a space between date and time in the posts

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#35]
There seems to be no space right now between the post date and publishing time:
https://www.dropbox.com/s/kjcf4s818pp2euk/Screenshot%202015-12-14%2010.06.19.png?dl=0

Could we add one?

**Comment by roborourke** [comment]
@petyaraykovska this one is a nod towards the code/dev based nature of the content, it's a machine readable format of a date most devs will be familiar with. Call it a stylistic choice :)

**Comment by petyaraykovska** [comment]
sigh... 

closing.
