### ISSUE TITLE
/thanks/ is 404ing

### ISSUE THREAD

**Issue by smckeown** [humanmade/feelingrestful-theme#36]
There is a thank you page that people are redirected to after buying a ticket but it is 404ing: https://feelingrestful.com/thanks/

Needs to be fixed.

**Comment by tareiking** [comment]
@smckeown / @petyaraykovska - The correct thanks page URL is https://feelingrestful.com/page/thanks/ (includes `/page/` in slug).
1. There is currently no content on the thanks page 
2. Not sure where to change the thanks URL (presuming EventBrite account?)

**Comment by smckeown** [comment]
1. There should be content. There used to be. It looks all screwy on the back end now though:

![](https://cldup.com/2Pnv1VCOdz.png)
1. Yeah, it's linked to from the EventBrite account

**Comment by roborourke** [comment]
@smckeown @tareiking think the standard page editor content was lost after the switch to modular page builder, it's there but not in page builder - @tareiking you could extract that from the db directly maybe and paste into a page builder text module.

Failing that Siobhan if you have the content for the thanks page elsewhere you can add a text module and add the content there to get it live again.

**Comment by mattheu** [comment]
I think there's a WP-CLI command to do this already. Let me double check...

**Comment by petyaraykovska** [comment]
Should I create the page and add some text?

**Comment by roborourke** [comment]
@petyaraykovska no, the page is there but the link to send people to in eventbrite needs to be updated, Matt's sorting the content out by the looks of it

**Comment by smckeown** [comment]
I've updated the link on eventbrite 

http://siobhanmckeown.com

**Comment by joehoyle** [comment]
We still have the old site at https://feelingrestful-old.hmn.md/thanks/ to can grab the content from there

**Comment by tareiking** [comment]
Thanks @joehoyle and @sanchothefat - I've added the text content from the old site and updated the links. What I haven't added is the newsletter signup link as the form was unstyle, instead, I dropped int the twitter widget.

@smckeown - is the newsletter signup still required?

**Comment by roborourke** [comment]
Main issue here is resolved - add a new one if we need it for the newsletter
