### ISSUE TITLE
News feed is limited to 10 posts and no pagination is available

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#37]
Currently our news page only shows the last 10 posts: https://feelingrestful.com/news/

Could we please either:
- Add pagination at the bottom of the page so that olders posts can be browsed

or
- Allow for at least 10 more posts to be displayed on the news page. 

Whichever is easier. Pagination would be better.

**Comment by petyaraykovska** [comment]
Just adding a small comment to clarify that I already tried increasing the number of posts in the Settings/Reading section of the admin, but it didn't change the result.

**Comment by roborourke** [comment]
Whoops! good shout

**Comment by petyaraykovska** [comment]
This is now a P1 as it also affects the sponsors list and prevents us from adding new sposnors.

**Comment by roborourke** [comment]
I'm thinking no pagination for sponsors would be best here, fine for news though

**Comment by petyaraykovska** [comment]
No pagination for sponsors please :)

**Comment by joehoyle** [comment]
yeah, let's just set the `per_page` query var to 100 or somethitng

**Comment by joehoyle** [comment]
Fixed
