### ISSUE TITLE
Open Graph issues

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#42]
Could we maybe fix some of these:
- Posts are shared without a description (before there was a general one that could be edited, not all there is is the title)
- Post are shared with the square site icon as a default picture, could there be an option for posts to get their featured image and if there isn't one, to have a specific size of image for Facebook? Squares don't really work there

**Comment by roborourke** [comment]
@petyaraykovska it'll use the generic site description field from general settings. For posts it'll use an excerpt, either generated or automatic. Posts should have their featured image already

**Comment by petyaraykovska** [comment]
@sanchothefat It doesn't though. There is a site description set but Facebook only grabs the site title. There's no description for links.

**Comment by petyaraykovska** [comment]
@sanchothefat Sorry, it grabs the post title. But no description. Here's a screenshot. 
<img width="653" alt="screenshot 2015-12-21 16 09 05" src="https://cloud.githubusercontent.com/assets/1880844/11933624/3942ffc0-a7fd-11e5-8a3b-aceb8eb317d6.png">

**Comment by sambulance** [comment]
@petyaraykovska I've uploaded a fix which I've asked Rob and/or Joe to review. Do you have a replacement image for the thumbnail?

**Comment by petyaraykovska** [comment]
Hey Sam, yeah, we can use this one:

https://www.dropbox.com/s/kp2c98iam2efi16/ADOR_logo.png?dl=0
