### ISSUE TITLE
Prettylinks don't work

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#43]
There's a URL rewrite issue on the schedule page: links go to prettylinks, e.g. `/speakers/rachel-baker`, but those aren't found (with an alert): only ID-based urls like `/speakers/84` work.

![pasted image at 2015_12_28 04_38 pm](https://cloud.githubusercontent.com/assets/1880844/12031514/7bad881c-ae15-11e5-8637-4d876fe084c1.png)
example at https://feelingrestful.com/speakers/rachel-baker/

**Comment by joehoyle** [comment]
`https://feelingrestful.com/speakers/rachel-baker/` has never been a URL that worked - what was linking to that? Seems like the links on the schedule post/page should just be updated to linked to real links (/speakers/84)?

**Comment by petyaraykovska** [comment]
I updated the post. 

I don't know how I came up with the urls, I usually don't trust my self with typing a url in so instead I just copy paste from the pages. Might be a leftover from the previous theme somewhere. It should work now. Closing.
