### ISSUE TITLE
Fix the sponsors logos on the homepage or turn to white logos on the sponsors page

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#44]
Sponsors logos on the homepage need to be fixed. If P1 issues had a priority, this would be the top one. 

The current logos on the homepage are automatically turned white, but that's not working for some of them and this needs to be fixed asap:

Options: 
- Turn all sponsors logos on the site white - that will require some CSS work in the Sponsors page to remove the white background of current logos
- Add a separate fields to the sponsors post type for the white logos on the homepage where we upload the right white logos. 

Rob, Joe, Noel, please advise on which approach you'd like to take so that I can specify the issue.

We need to get this sorted by the end of this week as the closer we get to the event, the more evident the wrong logos on the homepage are. 

cc/ @sanchothefat @noeltock

**Comment by joehoyle** [comment]
I added a new field "White logo" for each sponsor that will be shown on the home page (and fallback to the main logo if a white one doesn't exist). You can also now add a URL for a sponsors, which the logo on the sponsors page will link out to, per @smckeown's request.

**Comment by petyaraykovska** [comment]
Might be just me, but I can't see the white logo field, Joe. I flushed my cache and saw the coloured logos, but the field is still missing on the backend.

**Comment by noeltock** [comment]
Couldn't see either.

**Comment by petyaraykovska** [comment]
@joehoyle Mind if I reopen this until we figure out the mystery with the white logo field?

**Comment by joehoyle** [comment]
My bad, fixed now, see https://feelingrestful.com/wp-admin/post.php?post=1441&action=edit
