### ISSUE TITLE
Post list and schedule don't work on mobile

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#48]
I suspect it's the schedule table that breaks the post list in "News" on mobile as that's the only post that's also broken after opening it separately.

As the event is coming up and we will be sending people to the schedule during the day, could someone help out to fix this?

**Comment by petyaraykovska** [comment]
![image](https://cloud.githubusercontent.com/assets/1880844/12348288/75c9bc16-bb6e-11e5-8bfa-5ecb57a3773c.png)
![image](https://cloud.githubusercontent.com/assets/1880844/12348289/75ca843e-bb6e-11e5-8ad5-09d8f3497549.png)

**Comment by joehoyle** [comment]
You had a table in the schedule post where it was hardcoded to 700px width - you can't do that, otherwise it wont shrink on mobile. I updated it to be 100% width. That seems to have fixed the news page too, as I think the schdule post is shown on there too somewhere.

**Comment by petyaraykovska** [comment]
Thanks, Joe!
