### ISSUE TITLE
Allow Twitter timeline on contact page

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#5]
I created a widget with the Feelingrestful twitter timeline. Let's allow it to be displayed on https://feelingrestful.com/page/contact/

code: https://www.dropbox.com/s/jm7p043l9ufb78c/feelingrestful%20twitter.rtf?dl=0

**Comment by joehoyle** [comment]
@petyaraykovska I added a new page builder module for twitter timeline, and added it to the bottom of the contact page. You can configure it with a different twitter widget ID if you want too.
