### ISSUE TITLE
Change "Get ticket" to "Watch video" on the homepage

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#50]
Let's remove the Get your ticket text from the homepage and instead insert a "Watch video" link to the Post Status page dedicated to the event. 

This will require the first video to be uploaded, so also depends on when Brian will do it.

**Comment by pdewouters** [comment]
@petyaraykovska in the meantime I removed the button.

**Comment by petyaraykovska** [comment]
thanks Paul!
