### ISSUE TITLE
WP REST API response times 

### ISSUE THREAD

**Issue by xanderseren** [humanmade/feelingrestful-theme#53]
How are you achieving such fast response times for the WP Rest api requests? What is your caching setup like? Redis/Memcached? I'm in the process of using a similar infrastructure for a site I'm building am running into 2s+ response times (even locally!).

**Comment by joehoyle** [comment]
@xanderseren we're using a persistent object cache on the backend (memcached in this case). We're also using PHP 7 I think on this site. Also, be sure to not too expensive API calls like adding `_embed` when it's not needed, and `posts_per_page=500` or something like that!

If you are getting 2 second response times locally, that certainly sounds very bad, you should ideally always be running memcached/redis on any setup and MySQL Query caching. You can even flat cache the API responses for this kind of site should you wish.
