### ISSUE TITLE
Speakers page layout on mobile

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#7]
Speakers page doesn't quite work on mobile unless that was the intended layout?

There's a huge gap underneath the pictures before the code starts as well. What are the thoughts here?

![photo 9 11 15 11 01 38](https://cloud.githubusercontent.com/assets/1880844/11029692/5ebbe606-86d1-11e5-8393-678559560e47.png)

**Comment by noeltock** [comment]
Fixed. Pending @joehoyle to deploy
