### ISSUE TITLE
Add subtitles for the speakers companies 

### ISSUE THREAD

**Issue by petyaraykovska** [humanmade/feelingrestful-theme#8]
The companies of the speakers are a huge selling point for the conference for people who are not that involved in the WordPress community and are not so familiar with our speakers' names.

They need to be added and highlighted as they were on the last site:
- On the speakers page: https://feelingrestful.com/speakers/
- On individual speakers profiles: https://feelingrestful.com/speakers/89

**Comment by joehoyle** [comment]
Fixed
